name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify lock file
        run: |
          if [ ! -f package-lock.json ]; then
            echo "::error::package-lock.json not found! Commit your lock file first."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: pnpm ci --audit=false
        env:
          CI: true

      - name: Lint code
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Build production
        run: pnpm run build
        env:
          VITE_APP_VERSION: ${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
